### ISSUE TITLE
AP-8 Idea Review

### ISSUE THREAD

**Issue by md-agathisproject** [agathis-project/agathis-project#12]
**AP-8 AP Guideline** is at **idea state** and needs to be reviewed to move it to **draft state**.

Please review the pull request *AP-8 Guideline* #9  and **VOTE** (comment below) on this issue (follow AP-9) ; the merge will be completed after a positive result.

**Comment by jonsnow1357** [comment]
+1

**Comment by md-agathisproject** [comment]
review completed with approval; pull request completed with merge.
