### ISSUE TITLE
AP-4 Idea Review

### ISSUE THREAD

**Issue by md-agathisproject** [agathis-project/agathis-project#13]
**AP-4 Root Module Microcontroller FW** is at **idea state** and needs to be reviewed to move it to **draft state**.

Please review the pull request **AP-4 Root Module Microcontroller FW** #11 and VOTE (comment below) on this issue (follow AP-9) ; the merge will be completed after a positive result.

**Comment by jonsnow1357** [comment]
+1

the AP-4 link on the main table should point to AP-4 folder not to the main repo folder

**Comment by md-agathisproject** [comment]
review completed with approval; pull request completed with merge.
