### ISSUE TITLE
AP-9 review

### ISSUE THREAD

**Issue by jonsnow1357** [agathis-project/agathis-project#17]
standard time limit for review (5 days)

https://github.com/agathis-project/agathis-project/blob/master/AP-9/AP-9.md

**Comment by md-agathisproject** [comment]
AP-8 is not blessed yet (awaiting for comments in pull request) - but shouldn't the review happen as a final stage of the pull request? if so - then a correction is needed in 3.1 (1 pull request and 0 issue open - or rephrase)

**Comment by jonsnow1357** [comment]
ok, let's not forget how and why we started AP-9 - it's supposed to be a procedure that will apply to any type of AP (documentation, HW, SW).

So there is no separate pull request because it has to be clear what is being reviewed (no multiple branches) and it's supposed to happen after it has been worked on, and it should require only voting, not changes.
or, again we can just drop the whole formal review thing and just have master and branches ...

**Comment by md-agathisproject** [comment]
may need to put this review on hold and seek agreement at the level of the **AP-8 Guideline**, which is in pull request now.

**Comment by jonsnow1357** [comment]
AP-9 will be deleted and the content included in AP-9
