### ISSUE TITLE
Lab Setup

### ISSUE THREAD

**Issue by jonsnow1357** [agathis-project/agathis-project#18]
It is expected that the work on this project will include participants spread across different locations, and some will need access to the actual HW developed by the project. This document specifies the current lab setup used and the methods to allocate and access the equipments in the lab.

@admin

**Comment by md-agathisproject** [comment]
As there are no questions on this idea (we have to do it and the scope is quite clear), I already created the repo and the readme template; I promoted the AP-6 directly to _Draft_ state; please create a branch named Draft and use it.
I updated the title to be more specific: "Lab Setup" changed into "Remote Test Station"; feel free to revert it back if disagree with the change.

This issue will be closed in 5 days if no other comments.
