### ISSUE TITLE
AP-8 AP Purpose and Guidelines review request

### ISSUE THREAD

**Issue by md-agathisproject** [agathis-project/agathis-project#4]
- Need a review of the AP-8 *AP Purpose and Guidelines*;
- test here a github feature; this is kind of "attention to" - who needs to review it:
@eemitev 
@jonsnow1357

- the review to be done as comments added to this issue.
- the review does not have a deadline; it has Next Action label to mark it for action when possible.
- lets see how it goes.

**Comment by md-agathisproject** [comment]
- moved AP-8 under its [own folder](https://github.com/agathis-project/agathis-project/tree/master/AP-8) under agathis-project repo
- added a [flowchart diagram](https://github.com/agathis-project/agathis-project/blob/master/AP-8/AP-8-1.png);
- the flowchart will take precedence - the text will adapt to support the diagram.
- the diagram will be included into the AP-8 as a picture.

**Comment by jonsnow1357** [comment]
I think it would be more logical if the sections are in this order:
- What is AP?
- AP Types
- AP states (can be probably combined with types above)
- Work Flow
- AP Structure
... and so on

also wouldn't it be better to make a pull request for all the typos (or rephrasing) and then the author can merge and figure out the final document rather that comment here for all the small stuff?

**Comment by md-agathisproject** [comment]
I agree with the sections reorder.

For the second part - lets call it "post editing" I see two options:
1. let's try it right away. 
2. postpone it after main review is completed - triggered by the author's call for post-editing; in this sequence me may flush all mistakes in one sweep; I know I can be really picky/rigid/stubborn at the idea level, but loose and full of mistakes at the detail level.

As a general approach - what if we have a question period? (the doc for review may have a lot of new information and a learning period is needed) 

I would even try the pull request for the whole review; I hope it won't go too messy.
It should work fine if reviewers kick in fast - maybe  with a comment to specify a time window (start stop) or decline the participation to allow for a loose synchronization.
If that's happening - then I can quiet my mind and drop the pen until the review is complete.

**Comment by md-agathisproject** [comment]
**About AP workflow and HW design workflow.**

As you know - the APs were inspired from PEPs from Python.org; obviously SW centric and most likely the HW word never cross their mind when they put it together. Even I had only a sky high thought on how this will actually apply to HW design.

Now - I got to the point where the rubber meets the road: while writing the AP for the root hw, I realized it difficult to fit the AP workflow for the HW design.
**Solution**: Need to have the following stops/**reviews for the HW design**:
- idea/concept review
- design specifications review
- schematic review
- layout placement and mechanical preliminary review
- layout routing and mechanical final review
- prototype build review
- verification test review
- integration test review

The AP for hw designs would include equivalent **chapters** such as:
- idea
- design
- schematic
- layout 
- mechanicals
- prototype
- verification
- integration

After much thought, I came to this **proposal**: the state of this AP-8 should be demoted to "Idea" state, including suggestions and corrections as they come along and call the Idea review after we get a bit smarter - I mean we need to pass through one or two design cycles in this "remote" kind of operation. I'm guessing a number of tigers will jump our ways through this journey anyways and this AP will need to be updated.

Any other ideas?

**Comment by jonsnow1357** [comment]
How about ...
AP Types:
- documentation (like this one)
- HW/Mech development
- SW development

Each one with specific states, workflows and maybe formats. Keep number of states to a minimum for every type.
The main AP-8 will describe the documentation part and the review process that applies to all. Specifics for the other types can be attached later.

What I think we should pin down right now is the review. Since we're using github, we can start looking at these links

https://guides.github.com/activities/hello-world/#pr
https://help.github.com/articles/about-pull-requests/

**Comment by md-agathisproject** [comment]
After a discussion over the phone to expedite the conclusion - we came with the following plan:
- AP-8 will retain only the **purpose** and a very high level of the guideline for the workflow - to take care only about the _Process_ and _Informational_ AP types.
- A new AP titled "HW Design Guidelines" (by md) will be created to support and take advantage of the work on the root module.
- later, when we get more into SW stuff, we'll deal with a dedicated SW Design Guidelines.
- A new AP titled "Review Process" or similar (by jon) will be created to support the review process taking advantages of github features and recommendations - see links in comment above.

**Comment by md-agathisproject** [comment]
Follow-up on previous comment:
- AP-9 Review Process was created
- AP-8 updated.
- creation of HW Design Guidelines is pending.

**Comment by md-agathisproject** [comment]
jon-md meeting notes:
- AP-8 and AP-9 must update with synergy
  - clarified the definitions for the review and what labels to be used; no milestones.
  - clarified what idea is - and the fact we are not following the APs strictly - just yet.
  - remove the arbiters from AP-8
  - use a time limit to exit the review: AP-9

**Comment by md-agathisproject** [comment]
- I'm closing this issue; 
- it fulfilled initial scope;
- more or less formal - the AP-8 is in Draft state, work in progress.
- from now-on, will try to follow its guideline to drive this AP-8 to release state.
